"""
CUB-200-2011 Dataset Mapping and Taxonomy Information.

This module provides the complete 200-class list for the Caltech-UCSD Birds-200-2011 dataset
indexed from 0 to 199, along with taxonomic lookup capabilities.
"""

from typing import Dict, Any

CUB_CLASSES = [
    "001.Black_footed_Albatross",
    "002.Laysan_Albatross",
    "003.Sooty_Albatross",
    "004.Groove_billed_Ani",
    "005.Crested_Auklet",
    "006.Least_Auklet",
    "007.Parakeet_Auklet",
    "008.Rhinoceros_Auklet",
    "009.Brewer_Blackbird",
    "010.Red_winged_Blackbird",
    "011.Rusty_Blackbird",
    "012.Yellow_headed_Blackbird",
    "013.Bobolink",
    "014.Indigo_Bunting",
    "015.Lazuli_Bunting",
    "016.Painted_Bunting",
    "017.Cardinal",
    "018.Spotted_Catbird",
    "019.Gray_Catbird",
    "020.Yellow_breasted_Chat",
    "021.Eastern_Towhee",
    "022.Chuck_will_Widow",
    "023.Brandt_Cormorant",
    "024.Red_faced_Cormorant",
    "025.Pelagic_Cormorant",
    "026.Bronzed_Cowbird",
    "027.Shiny_Cowbird",
    "028.Brown_crested_Flycatcher",
    "029.Acadian_Flycatcher",
    "030.Great_Crested_Flycatcher",
    "031.Least_Flycatcher",
    "032.Olive_sided_Flycatcher",
    "033.Scissor_tailed_Flycatcher",
    "034.Vermilion_Flycatcher",
    "035.Yellow_bellied_Flycatcher",
    "036.Northern_Flicker",
    "037.Acorn_Woodpecker",
    "038.Downy_Woodpecker",
    "039.Hairy_Woodpecker",
    "040.Red_bellied_Woodpecker",
    "041.Red_headed_Woodpecker",
    "042.Red_cockaded_Woodpecker",
    "043.White_headed_Woodpecker",
    "044.Frigatebird",
    "045.Northern_Fulmar",
    "046.Gadwall",
    "047.American_Goldfinch",
    "048.European_Goldfinch",
    "049.Boat_tailed_Grackle",
    "050.Eared_Grebe",
    "051.Horned_Grebe",
    "052.Pied_billed_Grebe",
    "053.Western_Grebe",
    "054.Blue_Grosbeak",
    "055.Evening_Grosbeak",
    "056.Pine_Grosbeak",
    "057.Rose_breasted_Grosbeak",
    "058.Pigeon_Guillemot",
    "059.California_Gull",
    "060.Glaucous_winged_Gull",
    "061.Heermann_Gull",
    "062.Herring_Gull",
    "063.Ivory_Gull",
    "064.Ring_billed_Gull",
    "065.Slaty_backed_Gull",
    "066.Western_Gull",
    "067.Anna_Hummingbird",
    "068.Ruby_throated_Hummingbird",
    "069.Rufous_Hummingbird",
    "070.Green_Violetear",
    "071.Long_tailed_Jaeger",
    "072.Pomarine_Jaeger",
    "073.Blue_Jay",
    "074.Florida_Jay",
    "075.Green_Jay",
    "076.Dark_eyed_Junco",
    "077.Tropical_Kingbird",
    "078.Gray_Kingbird",
    "079.Belted_Kingfisher",
    "080.Green_Kingfisher",
    "081.Pied_Kingfisher",
    "082.Ringed_Kingfisher",
    "083.White_breasted_Kingfisher",
    "084.Red_legged_Kittiwake",
    "085.Horned_Lark",
    "086.Pacific_Loon",
    "087.Mallard",
    "088.Western_Meadowlark",
    "089.Hooded_Merganser",
    "090.Red_breasted_Merganser",
    "091.Mockingbird",
    "092.Nighthawk",
    "093.Clark_Nutcracker",
    "094.White_breasted_Nuthatch",
    "095.Baltimore_Oriole",
    "096.Hooded_Oriole",
    "097.Orchard_Oriole",
    "098.Scott_Oriole",
    "099.Ovenbird",
    "100.Brown_Pelican",
    "101.White_Pelican",
    "102.Western_Wood_Pewee",
    "103.Say_Phoebe",
    "104.American_Pipit",
    "105.Whip_poor_will",
    "106.Horned_Puffin",
    "107.Common_Raven",
    "108.White_necked_Raven",
    "109.Redpoll",
    "110.Loggerhead_Shrike",
    "111.Great_Grey_Shrike",
    "112.Baird_Sparrow",
    "113.Black_throated_Sparrow",
    "114.Brewer_Sparrow",
    "115.Chipping_Sparrow",
    "116.Clay_colored_Sparrow",
    "117.House_Sparrow",
    "118.Field_Sparrow",
    "119.Fox_Sparrow",
    "120.Grasshopper_Sparrow",
    "121.Harris_Sparrow",
    "122.Henslow_Sparrow",
    "123.Le_Conte_Sparrow",
    "124.Lincoln_Sparrow",
    "125.Nelson_Sparrow",
    "126.Savannah_Sparrow",
    "127.Seaside_Sparrow",
    "128.Song_Sparrow",
    "129.Tree_Sparrow",
    "130.Vesper_Sparrow",
    "131.White_crowned_Sparrow",
    "132.White_throated_Sparrow",
    "133.Cape_Glossy_Starling",
    "134.Bank_Swallow",
    "135.Barn_Swallow",
    "136.Cliff_Swallow",
    "137.Tree_Swallow",
    "138.Scarlet_Tanager",
    "139.Summer_Tanager",
    "140.Artic_Tern",
    "141.Black_Tern",
    "142.Caspian_Tern",
    "143.Common_Tern",
    "144.Elegant_Tern",
    "145.Forster_Tern",
    "146.Least_Tern",
    "147.Green_Tailed_Towhee",
    "148.Brown_Thrasher",
    "149.Sage_Thrasher",
    "150.Black_capped_Vireo",
    "151.Blue_headed_Vireo",
    "152.Philadelphia_Vireo",
    "153.Red_eyed_Vireo",
    "154.Warbling_Vireo",
    "155.White_eyed_Vireo",
    "156.Yellow_throated_Vireo",
    "157.Bay_breasted_Warbler",
    "158.Black_and_white_Warbler",
    "159.Black_throated_Blue_Warbler",
    "160.Black_throated_Green_Warbler",
    "161.Blue_winged_Warbler",
    "162.Canada_Warbler",
    "163.Cape_May_Warbler",
    "164.Cerulean_Warbler",
    "165.Chestnut_sided_Warbler",
    "166.Golden_winged_Warbler",
    "167.Hooded_Warbler",
    "168.Kentucky_Warbler",
    "169.Magnolia_Warbler",
    "170.Mourning_Warbler",
    "171.Myrtle_Warbler",
    "172.Nashville_Warbler",
    "173.Connecticut_Warbler",
    "174.Palm_Warbler",
    "175.Pine_Warbler",
    "176.Prairie_Warbler",
    "177.Prothonotary_Warbler",
    "178.Swainson_Warbler",
    "179.Tennessee_Warbler",
    "180.Wilson_Warbler",
    "181.Worm_eating_Warbler",
    "182.Yellow_Warbler",
    "183.Northern_Waterthrush",
    "184.Louisiana_Waterthrush",
    "185.Bohemian_Waxwing",
    "186.Cedar_Waxwing",
    "187.American_Three_toed_Woodpecker",
    "188.Pileated_Woodpecker",
    "189.Red_bellied_Woodpecker",
    "190.Red_cockaded_Woodpecker",
    "191.Red_headed_Woodpecker",
    "192.Downy_Woodpecker",
    "193.Bewick_Wren",
    "194.Cactus_Wren",
    "195.Carolina_Wren",
    "196.House_Wren",
    "197.Marsh_Wren",
    "198.Rock_Wren",
    "199.Winter_Wren",
    "200.Common_Yellowthroat"
]

TAXONOMY_RULES = [
    ("Albatross", ("Procellariiformes", "Diomedeidae", "Phoebastria")),
    ("Auklet", ("Charadriiformes", "Alcidae", "Aethia")),
    ("Blackbird", ("Passeriformes", "Icteridae", "Euphagus")),
    ("Bobolink", ("Passeriformes", "Icteridae", "Dolichonyx")),
    ("Bunting", ("Passeriformes", "Cardinalidae", "Passerina")),
    ("Cardinal", ("Passeriformes", "Cardinalidae", "Cardinalis")),
    ("Catbird", ("Passeriformes", "Mimidae", "Dumetella")),
    ("Chat", ("Passeriformes", "Icteriidae", "Icteria")),
    ("Cormorant", ("Suliformes", "Phalacrocoracidae", "Phalacrocorax")),
    ("Cowbird", ("Passeriformes", "Icteridae", "Molothrus")),
    ("Flycatcher", ("Passeriformes", "Tyrannidae", "Empidonax")),
    ("Flicker", ("Piciformes", "Picidae", "Colaptes")),
    ("Woodpecker", ("Piciformes", "Picidae", "Dryobates")),
    ("Frigatebird", ("Suliformes", "Fregatidae", "Fregata")),
    ("Fulmar", ("Procellariiformes", "Procellariidae", "Fulmarus")),
    ("Gadwall", ("Anseriformes", "Anatidae", "Mareca")),
    ("Goldfinch", ("Passeriformes", "Fringillidae", "Spinus")),
    ("Grackle", ("Passeriformes", "Icteridae", "Quiscalus")),
    ("Grebe", ("Podicipediformes", "Podicipedidae", "Podiceps")),
    ("Grosbeak", ("Passeriformes", "Cardinalidae", "Pheucticus")),
    ("Guillemot", ("Charadriiformes", "Alcidae", "Cepphus")),
    ("Gull", ("Charadriiformes", "Laridae", "Larus")),
    ("Hummingbird", ("Apodiformes", "Trochilidae", "Calypte")),
    ("Violetear", ("Apodiformes", "Trochilidae", "Colibri")),
    ("Jaeger", ("Charadriiformes", "Stercorariidae", "Stercorarius")),
    ("Jay", ("Passeriformes", "Corvidae", "Cyanocitta")),
    ("Junco", ("Passeriformes", "Passerellidae", "Junco")),
    ("Kingbird", ("Passeriformes", "Tyrannidae", "Tyrannus")),
    ("Kingfisher", ("Coraciiformes", "Alcedinidae", "Megaceryle")),
    ("Kittiwake", ("Charadriiformes", "Laridae", "Rissa")),
    ("Lark", ("Passeriformes", "Alaudidae", "Eremophila")),
    ("Loon", ("Gaviiformes", "Gaviidae", "Gavia")),
    ("Mallard", ("Anseriformes", "Anatidae", "Anas")),
    ("Meadowlark", ("Passeriformes", "Icteridae", "Sturnella")),
    ("Merganser", ("Anseriformes", "Anatidae", "Lophodytes")),
    ("Mockingbird", ("Passeriformes", "Mimidae", "Mimus")),
    ("Nighthawk", ("Caprimulgiformes", "Caprimulgidae", "Chordeiles")),
    ("Nutcracker", ("Passeriformes", "Corvidae", "Nucifraga")),
    ("Nuthatch", ("Passeriformes", "Sittidae", "Sitta")),
    ("Oriole", ("Passeriformes", "Icteridae", "Icterus")),
    ("Ovenbird", ("Passeriformes", "Parulidae", "Seiurus")),
    ("Pelican", ("Pelecaniformes", "Pelecanidae", "Pelecanus")),
    ("Pewee", ("Passeriformes", "Tyrannidae", "Contopus")),
    ("Phoebe", ("Passeriformes", "Tyrannidae", "Sayornis")),
    ("Pipit", ("Passeriformes", "Motacillidae", "Anthus")),
    ("Whip_poor_will", ("Caprimulgiformes", "Caprimulgidae", "Antrostomus")),
    ("Puffin", ("Charadriiformes", "Alcidae", "Fratercula")),
    ("Raven", ("Passeriformes", "Corvidae", "Corvus")),
    ("Redpoll", ("Passeriformes", "Fringillidae", "Acanthis")),
    ("Shrike", ("Passeriformes", "Laniidae", "Lanius")),
    ("Sparrow", ("Passeriformes", "Passerellidae", "Spizella")),
    ("Starling", ("Passeriformes", "Sturnidae", "Lamprotornis")),
    ("Swallow", ("Passeriformes", "Hirundinidae", "Hirundo")),
    ("Tanager", ("Passeriformes", "Cardinalidae", "Piranga")),
    ("Tern", ("Charadriiformes", "Laridae", "Sterna")),
    ("Towhee", ("Passeriformes", "Passerellidae", "Pipilo")),
    ("Thrasher", ("Passeriformes", "Mimidae", "Toxostoma")),
    ("Vireo", ("Passeriformes", "Vireonidae", "Vireo")),
    ("Warbler", ("Passeriformes", "Parulidae", "Setophaga")),
    ("Waterthrush", ("Passeriformes", "Parulidae", "Parkesia")),
    ("Waxwing", ("Passeriformes", "Bombycillidae", "Bombycilla")),
    ("Wren", ("Passeriformes", "Troglodytidae", "Troglodytes")),
    ("Yellowthroat", ("Passeriformes", "Parulidae", "Geothlypis")),
]


def clean_class_name(raw_name: str) -> str:
    """Converts '001.Black_footed_Albatross' to 'Black-footed Albatross'."""
    name_part = raw_name.split(".", 1)[-1]
    # Replace single underscores with spaces while maintaining standard hyphenated common names
    cleaned = name_part.replace("_", " ")
    
    # Common CUB-200 hyphenation replacements
    hyphen_words = ["Black footed", "Red winged", "Yellow headed", "Scissor tailed", 
                    "Yellow bellied", "Red faced", "Brown crested", "Olive sided", 
                    "Pied billed", "Glaucous winged", "Slaty backed", "Ring billed",
                    "Ruby throated", "Long tailed", "Dark eyed", "White breasted", 
                    "Red legged", "Red breasted", "White necked", "Black throated", 
                    "Clay colored", "White crowned", "White throated", "Green Tailed", 
                    "Black capped", "Blue headed", "Red eyed", "White eyed", 
                    "Yellow throated", "Bay breasted", "Black and white", "Blue winged", 
                    "Cape May", "Chestnut sided", "Golden winged", "Worm eating", 
                    "Three toed"]
    
    for word in hyphen_words:
        if word in cleaned:
            cleaned = cleaned.replace(word, word.replace(" ", "-"))
            
    return cleaned


def get_taxonomy_details(common_name: str) -> Dict[str, str]:
    """Derives Order, Family, and Genus for a given common bird name."""
    for keyword, (order, family, genus) in TAXONOMY_RULES:
        if keyword.lower() in common_name.lower():
            return {
                "order": order,
                "family": family,
                "genus": genus
            }
    
    words = common_name.split()
    genus = words[-1] if words else "Aves"
    return {
        "order": "Passeriformes",
        "family": "Aves",
        "genus": genus
    }


def get_cub_species_info(class_idx: int) -> Dict[str, Any]:
    """Given a 0-indexed class integer (0-199), returns full species metadata."""
    if not (0 <= class_idx < len(CUB_CLASSES)):
        raise ValueError(f"Class index {class_idx} out of range [0, {len(CUB_CLASSES)-1}]")

    raw_label = CUB_CLASSES[class_idx]
    common_name = clean_class_name(raw_label)
    taxonomy = get_taxonomy_details(common_name)
    
    # Construct clean scientific name
    species_epithet = common_name.split()[-1].lower()
    scientific_name = f"{taxonomy['genus']} {species_epithet}"

    return {
        "raw_label": raw_label,
        "common_name": common_name,
        "species": scientific_name,
        "taxonomy": taxonomy
    }